language: java

jdk:
  - openjdk11

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then cp .travis.settings.xml $HOME/.m2/settings.xml && mvn install -B -V -DskipTests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cp .travis.settings.xml $HOME/.m2/settings.xml && mvn install -B -V; fi'

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

branches:
  only:
    - master
