# in your application.yml file, express your bot identity something like the below:

symphony:
  bot:
    identity:
      email: evil.bot@example.com
      commonName: evil.bot.on.symphony
      # either specify as a p12...
      password: changeit
      location: file:./some.p12
      # or insert pems into your application.yml
      privateKey:  "-----BEGIN PRIVATE KEY-----\nMIIE...g3x6A==\n-----END PRIVATE KEY-----"
      certificates:
      - "-----BEGIN CERTIFICATE-----\nMIIC7z...xBXKt4=\n-----END CERTIFICATE-----"  